name: Vercel Deploy

on:
  push:
    branches:
      - main

jobs:
  pre-deploy-checks:
    name: Pre-deploy checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to project
        uses: actions/checkout@v4

      - name: Node.js set up
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install project dependencies
        run: yarn install

      - name: Code convention check
        run: yarn lint

  deploy:
    name: Deploy to Vercel
    needs: pre-deploy-checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to project
        uses: actions/checkout@v4

      - name: Setting environment variables
        run: |
          cp .env.example .env
          sed -i "s/API_SECRET_KEY=.*/API_SECRET_KEY=${{ secrets.API_SECRET_KEY }}/" .env

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
